name: RobbinvanDuivenboden
favicon: null
layout_spectrum: 0.9701859522610903
typography_spectrum: 0.3410376172978431
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9836152310017496
  lightness: 0.6382677520159632
  saturation: 0.19718622276559472
  rhythmicContrast: 0.1397938036825508
purpose: []
